
namespace :test do
  desc "Attempts to generate the list of methods"
  task :generate do
    $LOAD_PATH.unshift File.dirname(__FILE__)+'/../lib'
    require 'docapi'
    require 'rdoc/generator/docapi'
    Docapi::CLI.new.generate(["code/reference_api.rb"], "doc/2-documentation")
  end
  
  desc "Attempts to merge"
  task :merge do
    $LOAD_PATH.unshift File.dirname(__FILE__)+'/../lib'
    require 'docapi'
    require 'rdoc/generator/docapi'
    Docapi::CLI.new.merge(input = "doc", output = "output", :title => "Reference API Documentation")
  end
end
